app/request/utils.py
[Bugfix/OP-901](https://nycrecords.atlassian.net/browse/OP-901)
=> Bugfix/OP-901: ElasticSearch called when not enabled.

app/static/styles/request_info.css, app/templates/request/_view_request_info.html
Added word-wrap to request title, request description, and agency description (Tested and works in IE).
Scroll-bar for agency description no longer shows on IE if not required.
=> Bugfix/OP-911: Added wordwrap to request info section

app/response/utils.py, app/response/views.py, app/static/js/request/view-request-responses.js, app/static/styles/add_instruction.css, app/templates/request/responses/modal.html, app/templates/request/responses/modal_body/instructions.html, app/templates/request/responses/modal_body/notes.html, app/templates/response/add_extension.js.html, app/templates/response/add_file.js.html, app/templates/response/add_instruction.js.html, app/templates/response/add_link.js.html, app/templates/response/add_note.js.html
- Implemented Edit Offline Instructions response workflow in modal body.
- Added validation to return error message if no changes detected in edit responses workflow.
- Return confirmation header on confirmation page based on recipient of email.
=> Feature/OP-857: Edit Offline Instructions

app/response/views.py, app/static/js/request/main.js, app/templates/response/add_link.html, app/templates/response/add_link.js.html
- Removed link remote validator.
- Added strict url validator.
- Reverted" "Validate Link" button text back to "Next".
- Added TODOs for v2.1 feature checking link by returning status code.
- Updated add_link form fields to utilize global character count function.
=> Feature/OP-754: Create a Link

app/response/utils.py, app/response/views.py, app/static/js/request/view-request-responses.js, app/static/styles/base.css, app/templates/request/responses/modal_body/determinations.html, app/templates/request/responses/modal_body/instructions.html, app/templates/request/responses/modal_body/links.html, app/templates/request/responses/modal_body/notes.html, app/templates/response/add_extension.html, app/templates/response/add_extension.js.html, app/templates/response/add_file.html, app/templates/response/add_file.js.html, app/templates/response/add_instruction.html, app/templates/response/add_instruction.js.html, app/templates/response/add_link.html, app/templates/response/add_link.js.html, app/templates/response/add_note.html, app/templates/response/add_note.js.html
- Implemented Edit Link response workflow in modal body.
- Updated code and removed unnecessary divs in `notes.html` and `instructions.html`
=> Feature/OP-764: Edit Link

app/static/js/request/new-request-agency.js, app/static/js/request/new-request-anon.js, app/static/js/request/new-request-user.js, app/static/styles/new_request/new-request.css, app/templates/request/new_request_agency.html, app/templates/request/new_request_anon.html, app/templates/request/new_request_user.html
- Added Clear File button to clear file and filename.
- Updated `Choose File` input button to be bootstrap button.
- Added styles to `new-request.css` to update padding on new request page.
=> Bugfix/OP-909: Clear Upload File - Request a Record

app/request/utils.py, app/response/utils.py, app/static/js/request/view-request-responses.js, app/templates/email_templates/email_edit_private_response.html, app/templates/email_templates/email_edit_response.html, app/templates/email_templates/email_response_deleted.html, app/templates/email_templates/email_response_note.html, app/templates/email_templates/email_response_private_instruction.html, app/templates/email_templates/email_response_private_link.html, app/templates/email_templates/email_response_private_note.html, app/templates/response/add_file.js.html
- Fixed link to view request page in sent emails
=> Bugfix/OP-941: Email Broken Links

app/constants/__init__.py, app/lib/db_utils.py, app/models.py, app/request/forms.py, app/request/views.py, app/response/views.py, app/search/constants.py, app/search/utils.py, app/search/views.py, app/static/js/request/main.js, app/static/js/request/search.js, app/static/styles/base.css, app/static/styles/status.css, app/static/styles/view_all.css, app/templates/request/all.html, app/templates/request/result_row.html, app/templates/request/status.html, app/templates/request/view_request.html, app/templates/response/add_acknowledgment.js.html, app/templates/response/add_extension.js.html, config.py, requirements.txt, tests/lib/tools.py, tests/response.py
Includes additional search result information as a QA testing supplement (revealed on hover or by hitting "\\"). Will be removed after QA.
=> feature/OP-894 - View Requests / Search Page

app/request/utils.py, app/response/utils.py, app/static/js/request/view-request-responses.js, app/templates/email_templates/email_edit_file.html, app/templates/email_templates/email_edit_response.html, app/templates/email_templates/email_response.html, app/templates/request/responses/modal_body/files.html, tests/response.py
- Created function `handle_response_token` in class `Response Editor` to update response token expiration date.
- Created cached_propery function `get_file_link` to create link(s) for edit file workflow. 
- Refactored `RespFileEditor` and `_edit_email_handler` to get and generate proper email template  for edit file workflow.
=> Feature/OP-923: Update FILE Edit

app/templates/request/_edit_requester_info.html
-Set autocomplete="off" on submit button
=> Bugfix/OP-942: Edit user info. submit button disabled

app/__init__.py, app/lib/file_utils.py, app/lib/utils.py, app/request/utils.py, app/response/utils.py, app/response/views.py, app/static/js/request/view-request-responses.js, app/static/js/upload/fileupload.js, app/upload/utils.py, app/upload/views.py, clean_outgoing.py, config.py, crontab, manage.py, requirements.txt, tests/lib/tools.py, tests/response.py
To test in your virtual machine:
1. Update your requirements (you will probably have to yum-install some packages).
2. Create private-public key pair if you have not done so already (if `id_rsa` is not in `~/.ssh`):
```bash
cd ~/.ssh
ssh-keygen -t rsa
cat id_rsa.pub >> authorized_keys
sftp localhost  # this will prompt you to add localhost to the list of known hosts
exit
```
3. Set the required config constants in your `.env` file. You can use the following:
```bash
USE_SFTP=True
SFTP_HOSTNAME=localhost
SFTP_PORT=22
SFTP_USERNAME=vagrant
SFTP_RSA_KEY_FILE=/home/vagrant/.ssh/id_rsa
SFTP_UPLOAD_DIRECTORY=openrecords_v2_0
```
=> feature/OP-931 - SFTP File Handler

app/templates/request/new_request_agency.html, app/templates/request/new_request_anon.html, app/templates/request/new_request_user.html
Fixed Request Description box error.
=> Changed 'provide information' text error in request description boxes.

app/templates/navbar.html, app/templates/request/all.html
- Updated navbar **Report** to **Reports**
- Updated text in view all request page
=> Bugfix/OP-961: Homepage Report Label

app/constants/__init__.py, app/request/views.py
- Set Category default option to display "All"
=> Bugfix/OP-972: Category Default Display "All" on Select Field

app/__init__.py, app/constants/event_type.py, app/request/forms.py, app/request/views.py, app/response/utils.py, app/response/views.py, app/search/views.py, app/templates/email_templates/email_removed_user_request.html, app/templates/request/view_request.html, app/templates/response/remove_user_request.html, app/templates/response/remove_user_request.js.html, app/user_request/__init__.py, app/user_request/forms.py, app/user_request/utils.py, app/user_request/views.py
- Implemented remove user from request workflow
- Updated create_response_event method in `response.utils` to handle creating user request events
=> Feature/OP-860: Remove User from Request

app/main/views.py, app/templates/main/faq.html, app/templates/navbar.html
=> Created FAQ page

app/templates/request/all.html
Referenced their specific sections and added periods.
=> Fixed tooltip wording on the search page.

app/response/utils.py, app/static/styles/add_file.css, app/templates/request/responses/row.html, app/templates/response/add_file.html
In addition to acceptance criteria:
- Column size for response rows changed to account for the removal of the history section.
- Spacing between file rows in the Add File action has been decreased and the border behavior between rows has been improved.
=> bugfix/OP-987: change 'deleted' directory

app/templates/response/add_file.html
- Removed warning header for add file response
=> Bugfix/OP-968: Remove file warning header

app/templates/request/responses/modal.html, app/templates/response/add_acknowledgment.html, app/templates/response/add_closing.html, app/templates/response/add_extension.html, app/templates/response/add_file.html, app/templates/response/add_instruction.html, app/templates/response/add_link.html, app/templates/response/add_note.html
- Added title-bars and sub-headings for response actions
=> Bugfix/OP-963: Edit Email Window in action buttons

app/response/utils.py, app/templates/email_templates/email_response_instruction.html, app/templates/email_templates/email_response_link.html, app/templates/email_templates/email_response_private_link.html, app/templates/response/add_acknowledgment.html, app/templates/response/add_acknowledgment.js.html, app/templates/response/add_closing.html, app/templates/response/add_closing.js.html, app/templates/response/add_extension.html, app/templates/response/add_extension.js.html, app/templates/response/add_file.html, app/templates/response/add_file.js.html, app/templates/response/add_instruction.html, app/templates/response/add_instruction.js.html, app/templates/response/add_link.html, app/templates/response/add_link.js.html, app/templates/response/add_note.html, app/templates/response/add_note.js.html
- Updated confirmation headers for adding responses
=> Bugfix/OP-948: Update Confirmation Page Header for Add Response

app/models.py, app/permissions/utils.py, app/request/api/views.py, app/request/views.py, app/static/js/request/main.js, app/static/js/upload/fileupload.js, app/templates/request/_edit_requester_info.html, app/templates/request/_view_request_info.html, app/templates/request/view_request.html, app/templates/response/add_acknowledgment.js.html, app/templates/response/add_closing.js.html, app/templates/response/add_denial.js.html, app/templates/response/add_extension.js.html, app/templates/response/add_file.js.html, app/templates/response/add_instruction.js.html, app/templates/response/add_link.js.html, app/templates/response/add_note.js.html, app/upload/constants/__init__.py, app/upload/views.py
also stops ajax caching, IE upload cap, and adds more allowed mimetypes
=> bugfix/OP-1010: prevent double submit

app/templates/response/add_user_request.js.html, app/templates/response/edit_user_request.js.html
- Updated `add_user_request.js.html` and `edit_user_request.js.html` jquery selectors to make previously identical ids to be unique to the specific form.
=> Bugfix/OP-1026: Edit User options unavailable

app/templates/request/all.html, app/templates/request/view_request.html, app/templates/response/add_closing.html, app/templates/response/add_extension.html, app/templates/response/add_file.html, app/templates/response/add_instruction.html, app/templates/response/add_link.html, app/templates/response/add_note.html, app/templates/response/add_user_request.html, app/templates/response/edit_user_request.html, app/templates/response/remove_user_request.html
Fixed tool tips in the search section and added new tooltips for the the admin only functions.
=> Added Tooltips and eddited wording for previous ones.

app/user_request/utils.py
- Fixed incorrect subject line for adding and editing users to a request.
=> Bugfix/OP-1029: Email Copy - wrong Subject Line

app/report/views.py, app/templates/report/reports.js.html
- Implemented permissions for filtering by user.
- Set max tick size on reports chart load to 10.
- Filter only by requests submitted to onboarded agencies.
=> Bugfix/OP-1030: Reports Page - 2 Issues

app/templates/_nyc_gov_footer.html, config.py
- Set global config for nyc.gov base link
=> Bugfix/OP-1006: Check nyc.gov footer links

app/templates/report/reports.html, app/templates/request/all.html, app/templates/request/new_request_agency.html, app/templates/request/new_request_anon.html, app/templates/request/new_request_user.html, app/templates/response/add_file.html
Added periods to following tooltips:
Explore Requests
Description Field
Alternate Contact Information
Category Field
Agency Field
Add File
And adds tooltips to the Reports page.
=> Added periods to tooltips

app/templates/response/add_acknowledgment.html, app/templates/response/add_denial.html
Added tooltips for acknowledging and denying new requests.
=> task/OP-1042: Created tooltips for Acknowledging and Denying a request

app/static/js/request/contact.js
Implemented auto-scroll to first error field in contact page
=> Bugfix/OP-996: Auto-Scroll to First Error

app/response/utils.py, app/templates/email_templates/email_user_request_added.html, app/templates/email_templates/email_user_request_removed.html, app/templates/response/edit_user_request.js.html
- Fixed bug to show added permissions in email.
- Also includes fix to allow setting permissions to none in edit user permissions.
=> Bugfix/OP-1033: Incomplete email 'body' in Events

app/templates/email_templates/email_edit_file.html, app/upload/views.py
Updated `upload.views` POST endpoint function to allow users with edit file permission to replace file.
=> Bugfix/OP-1046: Edit File Permission Does Not Allow User to Replace File

app/constants/__init__.py, app/response/utils.py, app/templates/response/edit_user_request.js.html, data/agencies.csv
- Updated agencies.csv with updated copy.
- Also includes fix to anonymous object in create_response_event.
- Also includes making check for if permissions are different in editing user permissions to be one line.
=> Task/OP-944: Add Categories

app/templates/email_templates/email_response_denial.html
=> Feature/OP-993: Update Email Copy

app/auth/views.py, app/response/views.py, app/templates/auth/ldap_login_form.html, app/templates/email_templates/email_private_file_upload.html, app/templates/request/responses/modal_body/determinations.html, app/templates/request/responses/row.html
Also includes fix for downloading a file when not logged in and displaying nothing instead of 'None' when a determination has no reason.
=> Bugfix/OP-1054: Fix link to file sent to agency users from add file

app/response/utils.py, app/templates/email_templates/email_edit_response.html
This also includes the missing edit responses email content.
=> Bugfix/OP-1063: Fix to Unformatted Date in Add File Email

app/static/js/request/search.js, app/templates/auth/ldap_login_form.html, app/templates/request/all.html
also adds `autocomplete="off"` on the login password field
=> bugfix/OP-1065: prevent searching with invalid dates and show error messages

app/request/api/utils.py, app/request/api/views.py, app/request/views.py, app/static/styles/request_info.css, app/templates/request/_view_request_info.html, app/templates/request/_view_request_info_x-editable.js.html
- Created function to create and store events object of editing request information.
- Updated request info javascript.
=> Fix to request title to show 'Private' if private

app/templates/request/_view_request_info_x-editable.js.html, app/templates/request/all.html
- Also includes wording change in view all requests page.
=> Bugfix/OP-1081: Fix to Edit Request Title

app/lib/date_utils.py, app/models.py, app/templates/email_templates/email_request_status_changed.html, app/user_request/forms.py, jobs.py, manage.py, migrations/custom/openrecords_v1.py
...and fix the negative days issue... again...
Also includes `app.lib.date_utils.fix_due_dates_for_new_york`function that should be run in shell.
=> bugfix/OP-1088: Condense request status report emails
